Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/07/2024
Var

    X, Y, SOMA: real

Inicio
   escreva("Valor de X: ", X)
   leia(X)
   escreva("Valor de Y: ", Y)
   leia(Y)
   escreva("Resultado: ", soma)
   
  soma<- X + Y
Fimalgoritmo